/** Output format for replacements. */
export type CaretTagFormat = "html" | "markdown" | "raw";

/** Built-in default portals use CDN URL shapes; omit for plain `baseUrl + id`. */
export type PortalProvider = "simple" | "tenor" | "imgur" | "giphy";

/** One portal entry: key is the name used after `^` (e.g. `giphy` in `^giphy:id`). */
export type PortalEntry = {
  /**
   * Base or prefix URL. For **`simple`** (default when `provider` is omitted), the image URL is
   * `normalizePortalUrl(url) + id`. For built-in **`tenor`**, **`imgur`**, **`giphy`**, `url` is
   * informational; real URLs are generated by CDN rules.
   */
  url: string;
  provider?: PortalProvider;
};

export type PortalMap = Record<string, PortalEntry>;

/**
 * Imgur size letter after the hash: `abcd123m` or `abcd123m.jpg` if the id includes **`.jpg`**.
 * See README **Imgur** for dimensions.
 */
export type ImgurSizeSuffix = "s" | "b" | "t" | "m" | "l" | "h";

/**
 * - **`auto`** — pick a suffix from **`htmlImageSize.maxWidth`** when it is `px` (see **`imgurSuffixForMaxWidthPx`**); otherwise **`m`**; **`original`** when width &gt; 1024px.
 * - **`original`** — no suffix (full-size `https://i.imgur.com/{hash}` or `…/{hash}.{ext}` when the id has an extension).
 * - **`s`** … **`h`** — force that thumbnail tier.
 */
export type ImgurThumbnailOption = "auto" | ImgurSizeSuffix | "original";

/** Filename under `https://media1.giphy.com/media/{id}/…` (GIF and related image assets). */
export type GiphyMediaVariant =
  | "giphy.gif"
  | "fixed_height_small.gif"
  | "fixed_height.gif"
  | "200.gif"
  | "downsized.gif"
  | "100w.gif";

/** Max dimensions for HTML `<img>` output; aspect ratio is preserved via CSS. */
export type HtmlImageSizeOptions = {
  /** CSS `max-width` (e.g. `260px`, `100%`). Default `260px`. */
  maxWidth?: string;
  /** CSS `max-height`. Omit by default (no max-height on the `<img>`). */
  maxHeight?: string;
};

/**
 * Allowed id suffixes when **`enableExtensions`** is **`true`** and **`acceptedExtensions`** is omitted.
 */
export const DEFAULT_ID_EXTENSIONS_WHEN_ENABLED = [
  "gif",
  "png",
  "jpg",
  "jpeg",
  "webp",
] as const;

export type CaretTagSettings = {
  /**
   * Named portals: `^name:id` or `^name:id:kebab-alt` (optional human-readable alt).
   * If omitted or empty, built-in defaults are used (Tenor, Imgur, Giphy).
   */
  portals?: PortalMap;
  /**
   * Output format. Default `html`.
   * - `html` — `<img src="…" … />` with **`alt`** only when a third segment is present; otherwise no **`alt`** (see `htmlImageSize`)
   * - `markdown` — `![id](url)`, or `![decoded](url)` when a third segment is present (**`decodeKebabAlt`** always; not a setting)
   * - `raw` — `https://…`
   */
  format?: CaretTagFormat;
  /**
   * When **`true`**, ids may include a file extension from **`DEFAULT_ID_EXTENSIONS_WHEN_ENABLED`**
   * unless you set **`acceptedExtensions`** (which overrides this). Default **`false`** — extensionless ids only.
   */
  enableExtensions?: boolean;
  /**
   * Exact allowlist when the `id` contains a dot (lowercase, without dot). If **set**, **`enableExtensions`** is ignored.
   * If **omitted** and **`enableExtensions`** is **`true`**, **`DEFAULT_ID_EXTENSIONS_WHEN_ENABLED`** is used.
   * If **omitted** and **`enableExtensions`** is **`false`**, no dotted ids are allowed.
   */
  acceptedExtensions?: string[];
  /**
   * When the id has no `.ext`, allow it only if true (still subject to safe-id rules).
   * Default `true` (e.g. Tenor slug ids). Set to `false` to require an explicit extension.
   */
  allowExtensionlessIds?: boolean;
  /**
   * Giphy CDN suffix under `…/media/{id}/`. Default **`giphy.gif`** (original).
   * See README table for **`fixed_height_small.gif`**, **`fixed_height.gif`**, **`200.gif`**, **`downsized.gif`**, etc.
   */
  giphyMediaVariant?: GiphyMediaVariant;
  /**
   * Imgur thumbnail size letter (`abcd123m` or `abcd123m.jpg` when the id includes **`.jpg`**). Default **`auto`** (from **`maxWidth`** in `px`, or **`m`** when width is not pixels).
   */
  imgurThumbnail?: ImgurThumbnailOption;
  /**
   * Optional CSS limits for HTML `<img>` output (`max-width`, optional `max-height`, `object-fit: contain`).
   * Default max-width `260px`; max-height is omitted unless you set `maxHeight`.
   */
  htmlImageSize?: HtmlImageSizeOptions;
  /**
   * When true, place each replacement on its own line: HTML uses `<br />` before and after;
   * markdown and raw use `\n\n` before and after.
   */
  imageBlock?: boolean;
  /**
   * When true (default), `transform()` fetches each emitted HTTPS image URL (HEAD/GET) to
   * verify a real image is returned and to reduce SSRF risk (see `isSsrfSafeUrl`). If the
   * check fails, the `^portal:id` segment is removed. Set to false for offline use with `transformSync()`.
   */
  validateImageResource?: boolean;
  /** Timeout in ms for each image check when `validateImageResource` is true. Default `10000`. */
  fetchTimeoutMs?: number;
};
